cc_binary(
    name = "async_downloader",
    srcs = ["async_downloader.cc",
    ],
    deps = [
        "//common/exception",
        "//common/range",
        "//common/response_code",
        "//common/s3_credentials",
        "//common/storage_uri",
        "//gcs:gcs",
        "//utils/logging",
    ],
)
