load("//old_toolchain:rules.bzl", "runai_cc_configure_toolchain", "runai_cc_autoconf_impl_x86", "runai_cc_autoconf_impl_arm64")

runai_cc_configure_toolchain("x86_64", runai_cc_autoconf_impl_x86)
runai_cc_configure_toolchain("aarch64", runai_cc_autoconf_impl_arm64)

register_toolchains(
    "//toolchain:x86_64_linux_toolchain",
    "//toolchain:aarch64_linux_toolchain",
)

# Add the necessary Starlark functions to fetch google-cloud-cpp.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Fetch the Google Cloud C++ libraries.
# NOTE: Update this version and SHA256 as needed.
http_archive(
    name = "google_cloud_cpp",
    sha256 = "10867580483cb338e7d50920c2383698f3572cc6b4c7d072e38d5f43755cbd80",
    strip_prefix = "google-cloud-cpp-2.37.0",
    url = "https://github.com/googleapis/google-cloud-cpp/archive/v2.37.0.tar.gz",
)

#grpc_extra_deps()

load("@google_cloud_cpp//bazel:workspace0.bzl", "gl_cpp_workspace0")

gl_cpp_workspace0()

load("@google_cloud_cpp//bazel:workspace1.bzl", "gl_cpp_workspace1")

gl_cpp_workspace1()

load("@google_cloud_cpp//bazel:workspace2.bzl", "gl_cpp_workspace2")

gl_cpp_workspace2()

load("@google_cloud_cpp//bazel:workspace3.bzl", "gl_cpp_workspace3")

gl_cpp_workspace3()

load("@google_cloud_cpp//bazel:workspace4.bzl", "gl_cpp_workspace4")

gl_cpp_workspace4()

load("@google_cloud_cpp//bazel:workspace5.bzl", "gl_cpp_workspace5")

gl_cpp_workspace5()

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "aws_sdk_cpp",
    init_submodules = True,
    recursive_init_submodules = True,
    remote = "https://github.com/aws/aws-sdk-cpp.git",
    build_file = "//:aws_sdk_cpp.BUILD",
    # Use the commit hash to allow bazel to cache the git repository.
    # tag = "1.11.321",
    commit = "a7683563d714cc6235255052b61991b70f80d0f0",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://github.com/bazel-contrib/rules_foreign_cc/tree/main/docs#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()
